postinst, postrm rewritten

diff --git a/debian/typo3-dummy.postinst b/debian/typo3-dummy.postinst
--- a/debian/typo3-dummy.postinst
+++ b/debian/typo3-dummy.postinst
@@ -6,17 +6,49 @@ set -e
 PACKAGE=typo3-dummy
 T3CONFDIR=/var/lib/$PACKAGE/typo3conf
 
+APACHE_22=
+APACHE_24=
+CONF=
+
+COMMON_STATE=$(dpkg-query -f '${Status}' -W 'apache2.2-common' 2>/dev/null | awk '{print $3}' || true)
+
+if [ "$COMMON_STATE" = "installed" ] || [ "$COMMON_STATE" = "unpacked" ] ; then
+    APACHE_22=1
+fi
+if [ -e /usr/share/apache2/apache2-maintscript-helper ] ; then
+    APACHE_24=1
+    CONF=".conf"
+    . /usr/share/apache2/apache2-maintscript-helper
+fi
+
+if [ "$1" = "configure" ] ; then
+    # Cleanup old links
+    if [ -L /etc/apache2/sites-available/typo3-dummy-directory -a ! -e /etc/apache2/sites-available/typo3-dummy-directory$CONF ]; then
+        mv /etc/apache2/sites-available/typo3-dummy-directory /etc/apache2/sites-available/typo3-dummy-directory$CONF
+    fi
+    if [ -L /etc/apache2/conf-available/typo3-dummy-directory -a -L /etc/apache2/sites-available/typo3-dummy-directory$CONF ]; then
+        rm /etc/apache2/conf-available/typo3-dummy-directory
+    fi
+
+    if [ -L /etc/apache2/sites-available/typo3-dummy-vhost -a ! -e /etc/apache2/sites-available/typo3-dummy-vhost$CONF ]; then
+        mv /etc/apache2/sites-available/typo3-dummy-vhost /etc/apache2/sites-available/typo3-dummy-vhost$CONF
+    fi
+    if [ -L /etc/apache2/conf-available/typo3-dummy-vhost -a -L /etc/apache2/sites-available/typo3-dummy-vhost$CONF ]; then
+        rm /etc/apache2/conf-available/typo3-dummy-vhost
+    fi
+fi
+
 if [ "$1" = "configure" ] ; then
 	if [ -d $T3CONFDIR ] ; then
 		rm -f $T3CONFDIR/temp_CACHED*
 	fi
 
-	for confdir in sites-available conf-available; do
-		if [ -d /etc/apache2/$confdir -a ! -f /etc/apache2/$confdir/typo3-dummy-directory -a ! -L /etc/apache2/$confdir/typo3-dummy-directory ]; then
-			ln -s /etc/typo3-dummy/apache-directory.conf /etc/apache2/$confdir/typo3-dummy-directory
+	for confdir in sites-available; do
+		if [ -d /etc/apache2/$confdir -a ! -f /etc/apache2/$confdir/typo3-dummy-directory$CONF -a ! -L /etc/apache2/$confdir/typo3-dummy-directory$CONF ]; then
+			ln -s /etc/typo3-dummy/apache-directory.conf /etc/apache2/$confdir/typo3-dummy-directory$CONF
 		fi
-		if [ -d /etc/apache2/$confdir -a ! -f /etc/apache2/$confdir/typo3-dummy-vhost -a ! -L /etc/apache2/$confdir/typo3-dummy-vhost ]; then
-			ln -s /etc/typo3-dummy/apache-vhost.conf     /etc/apache2/$confdir/typo3-dummy-vhost
+		if [ -d /etc/apache2/$confdir -a ! -f /etc/apache2/$confdir/typo3-dummy-vhost$CONF -a ! -L /etc/apache2/$confdir/typo3-dummy-vhost$CONF ]; then
+			ln -s /etc/typo3-dummy/apache-vhost.conf     /etc/apache2/$confdir/typo3-dummy-vhost$CONF
 		fi
 	done
 fi
@@ -39,41 +71,37 @@ dbc_generate_include_owner=www-data:www-data
 dbc_generate_include=php:/etc/typo3-dummy/debian-db.php
 dbc_go typo3-dummy $@
 
-COMMON_STATE=$(dpkg-query -f '${Status}' -W 'apache2.2-common' 2>/dev/null | awk '{print $3}' || true)
 
 db_get typo3-dummy/apache_mode
 if [ "$RET" = "vhost" ]; then
-    if [ -e /usr/share/apache2/apache2-maintscript-helper ] ; then
-        . /usr/share/apache2/apache2-maintscript-helper
-        apache2_invoke enconf typo3-dummy-vhost
-    elif [ "$COMMON_STATE" = "installed" ] || [ "$COMMON_STATE" = "unpacked" ] ; then
+    if [ -n "$APACHE_24" ] ; then
+        apache2_invoke ensite typo3-dummy-vhost
+    elif [ -n "$APACHE_22" ] ; then
         a2ensite typo3-dummy-vhost
     fi
 fi
 if [ "$RET" = "directory" ]; then
-    if [ -e /usr/share/apache2/apache2-maintscript-helper ] ; then
-        . /usr/share/apache2/apache2-maintscript-helper
-        apache2_invoke enconf typo3-dummy-directory
-    elif [ "$COMMON_STATE" = "installed" ] || [ "$COMMON_STATE" = "unpacked" ] ; then
+    if [ -n "$APACHE_24" ] ; then
+        apache2_invoke ensite typo3-dummy-directory
+    elif [ -n "$APACHE_22" ] ; then
         a2ensite typo3-dummy-directory
     fi
 fi
 
 if [ "$RET" = "vhost" -o "$RET" = "directory" ]; then
-    if [ -e /usr/share/apache2/apache2-maintscript-helper ] ; then
-        . /usr/share/apache2/apache2-maintscript-helper
+    if [ -n "$APACHE_24" ] ; then
         apache2_invoke enmod rewrite
-    elif [ "$COMMON_STATE" = "installed" ] || [ "$COMMON_STATE" = "unpacked" ] ; then
+    elif [ -n "$APACHE_22" ] ; then
         a2enmod rewrite
     fi
 
     db_get typo3-dummy/apache_restart
     if [ "$RET" = "true" ]; then
-        if [ "$COMMON_STATE" = "installed" ] || [ "$COMMON_STATE" = "unpacked" ] ; then
+        if [ -n "$APACHE_22" ] ; then
             apache2ctl restart
         fi
     fi
 fi
 
-#DEBHELPER#
 
+#DEBHELPER#
